# Generated by Django 6.0.4 on 2026-04-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
